/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.kerbalspaceprogram.kspmissioncontrol;

import javax.swing.JOptionPane;
import fr.kerbalspaceprogram.kspmissioncontrol.Telemetry.DataTelemetry;

/**
 *
 * @author Bruno
 */
public class NewChartDialog extends javax.swing.JDialog {

    private static int chartCount = 1;
    private final String probeName;
    private final String uid;
    
    /**
     * Creates new form NewJDialog
     */
    public NewChartDialog(java.awt.Frame parent, boolean modal, String uid, String probeName) {
        super(parent, modal);
        this.uid = uid;
        this.probeName = probeName;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        yAxisComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        xAxisComboBox = new javax.swing.JComboBox();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New chart");
        getContentPane().setLayout(new java.awt.GridLayout(0, 2));

        jLabel1.setText("Title");
        getContentPane().add(jLabel1);

        titleTextField.setText(this.probeName + " - untitled "  + String.valueOf(NewChartDialog.chartCount));
        getContentPane().add(titleTextField);

        jLabel3.setText("Y axis");
        getContentPane().add(jLabel3);

        yAxisComboBox.setModel(new javax.swing.DefaultComboBoxModel(Telemetry.DATA_LABEL));
        getContentPane().add(yAxisComboBox);

        jLabel2.setText("X axis");
        getContentPane().add(jLabel2);

        xAxisComboBox.setModel(new javax.swing.DefaultComboBoxModel(Telemetry.DATA_LABEL));
        getContentPane().add(xAxisComboBox);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        try {
            DataTelemetry x = (DataTelemetry) DataTelemetry.values()[this.xAxisComboBox.getSelectedIndex()];
            DataTelemetry y = (DataTelemetry) DataTelemetry.values()[this.yAxisComboBox.getSelectedIndex()];
            
            KspChart chart = new KspChart(this.uid, this.titleTextField.getText(), x, y);
            ((MainFrame) this.getParent()).addChart(this.uid, chart);
            NewChartDialog.chartCount++;
            this.dispose();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(NewChartDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage(), "New chart error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField titleTextField;
    private javax.swing.JComboBox xAxisComboBox;
    private javax.swing.JComboBox yAxisComboBox;
    // End of variables declaration//GEN-END:variables
}
